[package]
name = "apicheck_plugin"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
name = "apicheck_plugin"
crate-type = ["dylib"]

[dependencies]
json = "0.11"
libapicheck = {path="../libapicheck"}
