[package]
name = "apidiff"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
env_logger = "0.5"
json = "0.11"
log = "0.4"

[dependencies.clap]
version = "2"
default-features = false
