[package]
name = "libapicheck"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
term = "0.5"
json = "0.11"

[dependencies.syntax]
package = "rustc-ap-syntax"
version = "610.0.0"
